- name: Test SSH connection
  run: |
    ssh -p ${{ secrets.HOSTINGER_SSH_PORT }} \
      ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} \
      "ls -ld ${{ secrets.HOSTINGER_PATH }}"