on:
  push:
    branches:
      - production   # deploy only from production branch
jobs:
  deploy:
   runs-on: ubuntu-latest
   
   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup SSH
     run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
      chmod 600 ~/.ssh/id_ed25519
      ssh-keyscan -p ${{ secrets.HOSTINGER_SSH_PORT }} ${{ secrets.HOSTINGER_SSH_HOST }} >> ~/.ssh/known_hosts
  
   - name: Test SSH connection
     run: |
        ssh -p ${{ secrets.HOSTINGER_SSH_PORT }} \
          ${{ secrets.HOSTINGER_SSH_USER }}@${{ secrets.HOSTINGER_SSH_HOST }} \
          "ls -ld ${{ secrets.HOSTINGER_PATH }}"